### ISSUE TITLE
1-39-0 Crashes

### ISSUE THREAD

**Issue by Daboss7173** [Ao28th28/Ao28th28.github.io#6]
What went wrong:
1-39-0 Doesn't boot.

How can I replicate this:
Try to play 1-39-0

Console log output (optional):
Uncaught ReferenceError: Fabrique is not defined
    at e.create (game.min.js:43558:101)
    at c.StateManager.loadComplete (phaser.min.js:10:23055)
    at c.StateManager.preUpdate (phaser.min.js:10:19822)
    at c.Game.updateLogic (phaser.min.js:11:29027)
    at c.Game.update (phaser.min.js:11:27739)
    at c.RequestAnimationFrame.updateRAF (phaser.min.js:17:14931)
    at window.requestAnimationFrame.forceSetTimeOut._onLoop (phaser.min.js:17:14824)

You need to actually update the index.html for 1-39-0 from my site, it should boot then.

**Comment by Ao28th28** [comment]
Fixed, and the saves from 1-30-0 can be used.
